import Head from 'next/head';
import { getSession } from 'next-auth/react';

import Login from '../components/Login';
import Header from '../components/Header';
import Sidebar from '../components/Sidebar';
import Feed from '../components/Feed';
import RightSidebar from '../components/RightSidebar';

const Home = ({ session }) => {
  if (!session) {
    return <Login />;
  }
  return (
    <div>
      <Head>
        <title>Facebook Clone</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Header />

      <main className='flex bg-gray-100'>
        <Sidebar />
        <Feed />
        <RightSidebar />
      </main>
    </div>
  );
};

export default Home;

export const getServerSideProps = async context => {
  const session = await getSession(context);

  return {
    props: { session },
  };
};
